
#
#  Auto-generated file - do not edit manually
#  Generated by scripts/download_crds.sh
#
resource "kubernetes_manifest" "customresourcedefinition_bgpconfigurations_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/bgpconfigurations.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_bgpfilters_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/bgpfilters.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_bgppeers_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/bgppeers.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_blockaffinities_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/blockaffinities.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_caliconodestatuses_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/caliconodestatuses.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_clusterinformations_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/clusterinformations.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_felixconfigurations_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/felixconfigurations.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_globalnetworkpolicies_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/globalnetworkpolicies.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_globalnetworksets_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/globalnetworksets.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_hostendpoints_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/hostendpoints.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_ipamblocks_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/ipamblocks.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_ipamconfigs_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/ipamconfigs.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_ipamhandles_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/ipamhandles.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_ippools_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/ippools.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_ipreservations_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/ipreservations.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_kubecontrollersconfigurations_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/kubecontrollersconfigurations.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_networkpolicies_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/networkpolicies.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_networksets_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/networksets.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_stagedglobalnetworkpolicies_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/stagedglobalnetworkpolicies.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_stagedkubernetesnetworkpolicies_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/stagedkubernetesnetworkpolicies.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_stagednetworkpolicies_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/stagednetworkpolicies.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_tiers_crd_projectcalico_org" {
  manifest = yamldecode(file("${path.module}/tiers.crd.projectcalico.org.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_adminnetworkpolicies_policy_networking_k8s_io" {
  manifest = yamldecode(file("${path.module}/adminnetworkpolicies.policy.networking.k8s.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_baselineadminnetworkpolicies_policy_networking_k8s_io" {
  manifest = yamldecode(file("${path.module}/baselineadminnetworkpolicies.policy.networking.k8s.io.yaml"))
}

