
#
#  Auto-generated file - do not edit manually
#  Generated by scripts/download_crds.sh
#
resource "kubernetes_manifest" "customresourcedefinition_acceleratorclasses_ome_io" {
  manifest = yamldecode(file("${path.module}/acceleratorclasses.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_basemodels_ome_io" {
  manifest = yamldecode(file("${path.module}/basemodels.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_benchmarkjobs_ome_io" {
  manifest = yamldecode(file("${path.module}/benchmarkjobs.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_clusterbasemodels_ome_io" {
  manifest = yamldecode(file("${path.module}/clusterbasemodels.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_clusterservingruntimes_ome_io" {
  manifest = yamldecode(file("${path.module}/clusterservingruntimes.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_finetunedweights_ome_io" {
  manifest = yamldecode(file("${path.module}/finetunedweights.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_inferenceservices_ome_io" {
  manifest = yamldecode(file("${path.module}/inferenceservices.ome.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_servingruntimes_ome_io" {
  manifest = yamldecode(file("${path.module}/servingruntimes.ome.io.yaml"))
}

