
#
#  Auto-generated file - do not edit manually
#  Generated by scripts/download_crds.sh
#
resource "kubernetes_manifest" "customresourcedefinition_tenants_minio_min_io" {
  manifest = yamldecode(file("${path.module}/tenants.minio.min.io.yaml"))
}

