
#
#  Auto-generated file - do not edit manually
#  Generated by scripts/download_crds.sh
#
resource "kubernetes_manifest" "customresourcedefinition_cloudeventsources_eventing_keda_sh" {
  manifest = yamldecode(file("${path.module}/cloudeventsources.eventing.keda.sh.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_clustercloudeventsources_eventing_keda_sh" {
  manifest = yamldecode(file("${path.module}/clustercloudeventsources.eventing.keda.sh.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_clustertriggerauthentications_keda_sh" {
  manifest = yamldecode(file("${path.module}/clustertriggerauthentications.keda.sh.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_scaledjobs_keda_sh" {
  manifest = yamldecode(file("${path.module}/scaledjobs.keda.sh.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_scaledobjects_keda_sh" {
  manifest = yamldecode(file("${path.module}/scaledobjects.keda.sh.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_triggerauthentications_keda_sh" {
  manifest = yamldecode(file("${path.module}/triggerauthentications.keda.sh.yaml"))
}

