
#
#  Auto-generated file - do not edit manually
#  Generated by scripts/download_crds.sh
#
resource "kubernetes_manifest" "customresourcedefinition_rayclusters_ray_io" {
  manifest = yamldecode(file("${path.module}/rayclusters.ray.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_rayjobs_ray_io" {
  manifest = yamldecode(file("${path.module}/rayjobs.ray.io.yaml"))
}

resource "kubernetes_manifest" "customresourcedefinition_rayservices_ray_io" {
  manifest = yamldecode(file("${path.module}/rayservices.ray.io.yaml"))
}

